import React, { FC } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Container } from 'react-bootstrap'
import styles from './Header.module.scss'

interface IProps {
  title: string;
}

const Header: FC<IProps> = (
  {
    title,
  }
) => {
  return (
    <header>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={styles.container}>
        <Link href="/">
          <a>
            <Image src="/logo.svg" alt="logo" width={28} height={18} />
          </a>
        </Link>
        <Image src="/user.svg" alt="user" width={18} height={23} />
      </Container>
    </header>
  )
}

export default Header
